### ISSUE TITLE
Relative imports throw errors

### ISSUE THREAD

**Issue by plockaby** [tlocke/flake8-alphabetize#1]
Sorry to leave such a short bug report but I just tested this out and ran into this. If you use relative imports this tool throws errors. For example:

```
from . import logger
```

Throws this error:

```
(venv) plockaby@dev alpha % flake8
Traceback (most recent call last):
  File "/Users/plockaby/dev/alpha/venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/main/cli.py", line 22, in main
    app.run(argv)
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/main/application.py", line 363, in run
    self._run(argv)
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/main/application.py", line 351, in _run
    self.run_checks()
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/main/application.py", line 264, in run_checks
    self.file_checker_manager.run()
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/checker.py", line 323, in run
    self.run_serial()
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/checker.py", line 307, in run_serial
    checker.run_checks()
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/checker.py", line 589, in run_checks
    self.run_ast_checks()
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8/checker.py", line 494, in run_ast_checks
    for (line_number, offset, text, _) in runner:
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8_alphabetize/core.py", line 19, in __iter__
    errors = _find_errors(Alphabetize.app_names, self.tree)
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8_alphabetize/core.py", line 189, in _find_errors
    imports = [AzImport(app_names, imp) for imp in import_nodes]
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8_alphabetize/core.py", line 189, in <listcomp>
    imports = [AzImport(app_names, imp) for imp in import_nodes]
  File "/Users/plockaby/dev/alpha/venv/lib/python3.9/site-packages/flake8_alphabetize/core.py", line 110, in __init__
    dot_idx = m.find(".")
AttributeError: 'NoneType' object has no attribute 'find'
```

**Comment by tlocke** [comment]
Oops, thanks for reporting this, I'll have a look straight away.

**Comment by tlocke** [comment]
That should be fixed now. I've done a new release 0.0.13, so if you do a `pip install --upgrade flake8-alphabetize` it should fix it. Let me know if you have any problems.

**Comment by plockaby** [comment]
Looks good. One thing you might be interested in changing, though:

```
foobar/test.py:5:1: AZ100 Import statements are in the wrong order. 'import asdf' should be before 'from .None import logger'
```

The `from .None import logger` appears to be incorrect. But it works on any number of relative imports now. Thanks!

**Comment by tlocke** [comment]
Thanks, you're right. I've done a new release 0.0.14 that should fix that `from .None import logger` problem.
