### ISSUE TITLE
ValueError with flake8 6.0.0

### ISSUE THREAD

**Issue by Xefir** [tlocke/flake8-alphabetize#9]
When I run flake8 with no arguments with the latest flake8 and flake8-alphabetize, this stacktrace occurs : 

```
Traceback (most recent call last):
  File ".venv/bin/flake8", line 8, in <module>
    sys.exit(main())
  File ".venv/lib/python3.10/site-packages/flake8/main/cli.py", line 23, in main
    app.run(argv)
  File ".venv/lib/python3.10/site-packages/flake8/main/application.py", line 198, in run
    self._run(argv)
  File ".venv/lib/python3.10/site-packages/flake8/main/application.py", line 186, in _run
    self.initialize(argv)
  File ".venv/lib/python3.10/site-packages/flake8/main/application.py", line 165, in initialize
    self.plugins, self.options = parse_args(argv)
  File ".venv/lib/python3.10/site-packages/flake8/options/parse_args.py", line 51, in parse_args
    option_manager.register_plugins(plugins)
  File ".venv/lib/python3.10/site-packages/flake8/options/manager.py", line 259, in register_plugins
    add_options(self)
  File ".venv/lib/python3.10/site-packages/flake8_alphabetize/core.py", line 31, in add_options
    option_manager.add_option(
  File ".venv/lib/python3.10/site-packages/flake8/options/manager.py", line 281, in add_option
    self._current_group.add_argument(*option_args, **option_kwargs)
  File "/usr/lib/python3.10/argparse.py", line 1440, in add_argument
    raise ValueError('%r is not callable' % (type_func,))
ValueError: 'string' is not callable
```

Thank you :)

**Comment by tlocke** [comment]
Thanks for this @Xefir, this should be fixed in the release I've just done, version 0.0.19. Let me know if you still have any problems.
